// DRISHTI — Mock Data
// All simulated analysis results for the interactive prototype

export const MOCK_RESULTS = {
    image: {
        file_type: "image",
        file_name: "uploaded_image.jpg",
        overall_confidence: 0.78,
        verdict: "Likely AI-Generated",
        verdict_color: "red",
        processing_time_ms: 2340,
        sub_scores: { text: null, image: 0.81, audio: null, video: null, metadata: 0.94 },
        cmce_risk: "HIGH",
        cmce_detail: "No authentic camera metadata. GAN noise pattern detected in background pixel clusters. Lighting inconsistencies with scene depth.",
        gan_source: "Stable Diffusion XL",
        gan_confidence: 0.71,
        gan_version: "v1.0",
        viral_risk_score: 0.72,
        viral_risk_label: "High Spread Potential",
        indicators: {
            en: [
                { severity: "high", text: "Unnatural eye blinking cadence detected in facial region" },
                { severity: "high", text: "GAN noise fingerprint found in background pixel clusters" },
                { severity: "high", text: "EXIF metadata absent — typical of AI-generated images" },
                { severity: "medium", text: "Skin texture shows over-smoothing inconsistent with real photos" },
                { severity: "low", text: "Lighting direction on face does not match scene background" },
            ],
            hi: [
                { severity: "high", text: "चेहरे के क्षेत्र में असामान्य पलक झपकाने की लय पाई गई" },
                { severity: "high", text: "पृष्ठभूमि पिक्सल समूहों में GAN शोर फिंगरप्रिंट मिला" },
                { severity: "high", text: "EXIF मेटाडेटा अनुपस्थित — AI-जनित छवियों के लिए सामान्य" },
                { severity: "medium", text: "त्वचा की बनावट असंगत अत्यधिक चिकनाई दर्शाती है" },
                { severity: "low", text: "चेहरे पर प्रकाश की दिशा पृष्ठभूमि से मेल नहीं खाती" },
            ],
        },
        timeline: null,
        heatmap_zones: [
            { top: "18%", left: "28%", width: "24%", height: "18%", label: "Eye region anomaly" },
            { top: "62%", left: "10%", width: "36%", height: "22%", label: "Background GAN artifacts" },
            { top: "38%", left: "55%", width: "20%", height: "16%", label: "GAN noise cluster" },
        ],
    },

    video: {
        file_type: "video",
        file_name: "uploaded_video.mp4",
        overall_confidence: 0.86,
        verdict: "Deepfake Detected",
        verdict_color: "red",
        processing_time_ms: 8720,
        sub_scores: { text: null, image: 0.88, audio: 0.79, video: 0.91, metadata: 0.85 },
        cmce_risk: "CRITICAL",
        cmce_detail: "Severe mismatch between facial emotion and voice tone. Lip-sync delta exceeds 120ms threshold. Temporal boundary artifacts across 6 frames.",
        gan_source: "DeepFaceLab",
        gan_confidence: 0.83,
        gan_version: "v2.1",
        viral_risk_score: 0.88,
        viral_risk_label: "Critical Viral Risk",
        indicators: {
            en: [
                { severity: "high", text: "Facial emotion (neutral) contradicts voice tone (angry) — CMCE mismatch" },
                { severity: "high", text: "Lip-sync desynchronization at 00:04–00:07s (delta: 130ms)" },
                { severity: "high", text: "Temporal flickering artifacts in facial boundary between frames" },
                { severity: "medium", text: "Eye reflection inconsistency — light source changes mid-sentence" },
                { severity: "medium", text: "Audio prosody patterns match synthetic TTS voice model" },
            ],
            hi: [
                { severity: "high", text: "चेहरे का भाव (तटस्थ) आवाज़ (क्रोधित) से विरोधाभासी — CMCE असंगति" },
                { severity: "high", text: "00:04–00:07s पर होंठ-सिंक असंगति (डेल्टा: 130ms)" },
                { severity: "high", text: "फ्रेम के बीच चेहरे की सीमा में टेम्पोरल आर्टिफेक्ट" },
                { severity: "medium", text: "आँखों के प्रतिबिंब में असंगति — प्रकाश स्रोत बीच में बदलता है" },
                { severity: "medium", text: "ऑडियो पैटर्न AI वॉयस मॉडल से मेल खाता है" },
            ],
        },
        timeline: [
            { time: "0:00", score: 0.32 }, { time: "0:02", score: 0.45 }, { time: "0:04", score: 0.91 },
            { time: "0:06", score: 0.95 }, { time: "0:08", score: 0.88 }, { time: "0:10", score: 0.79 },
            { time: "0:12", score: 0.83 }, { time: "0:14", score: 0.86 }, { time: "0:16", score: 0.90 },
            { time: "0:18", score: 0.72 }, { time: "0:20", score: 0.68 },
        ],
        heatmap_zones: [
            { top: "14%", left: "30%", width: "28%", height: "22%", label: "Face swap boundary" },
            { top: "52%", left: "32%", width: "14%", height: "12%", label: "Lip region mismatch" },
        ],
    },

    audio: {
        file_type: "audio",
        file_name: "uploaded_audio.mp3",
        overall_confidence: 0.67,
        verdict: "Possibly Synthetic",
        verdict_color: "yellow",
        processing_time_ms: 1890,
        sub_scores: { text: null, image: null, audio: 0.67, video: null, metadata: 0.55 },
        cmce_risk: "MEDIUM",
        cmce_detail: "Unnatural prosody patterns. Formant transitions inconsistent with human speech. Background noise artificially absent.",
        gan_source: "ElevenLabs TTS",
        gan_confidence: 0.58,
        gan_version: "v2",
        viral_risk_score: 0.52,
        viral_risk_label: "Moderate Spread Potential",
        indicators: {
            en: [
                { severity: "high", text: "Unnatural prosody — pitch variation too uniform for human speech" },
                { severity: "high", text: "Formant transitions match ElevenLabs voice model signature" },
                { severity: "medium", text: "Background noise is artificially clean — real recordings have ambient noise" },
                { severity: "low", text: "Breath pattern regularity is statistically improbable for natural speech" },
            ],
            hi: [
                { severity: "high", text: "अप्राकृतिक प्रोसोडी — मानवीय भाषण के लिए पिच बहुत एकसमान" },
                { severity: "high", text: "फॉर्मेंट ट्रांजिशन ElevenLabs वॉयस मॉडल से मेल खाता है" },
                { severity: "medium", text: "पृष्ठभूमि शोर कृत्रिम रूप से साफ है" },
                { severity: "low", text: "सांस लेने का पैटर्न प्राकृतिक भाषण के लिए असंभव" },
            ],
        },
        timeline: null,
        heatmap_zones: [],
    },

    text: {
        file_type: "text",
        file_name: "uploaded_text.txt",
        overall_confidence: 0.91,
        verdict: "AI-Written Content",
        verdict_color: "red",
        processing_time_ms: 890,
        sub_scores: { text: 0.91, image: null, audio: null, video: null, metadata: null },
        cmce_risk: "HIGH",
        cmce_detail: "Perplexity score extremely low (42.3). Token probability distribution matches GPT-4. Burstiness score indicates non-human authorship.",
        gan_source: "GPT-4 / ChatGPT",
        gan_confidence: 0.87,
        gan_version: "GPT-4o",
        viral_risk_score: 0.65,
        viral_risk_label: "High Spread Potential",
        indicators: {
            en: [
                { severity: "high", text: "Perplexity score: 42.3 — far below average human writing (150–200)" },
                { severity: "high", text: "Token probability distribution closely matches GPT-4 output patterns" },
                { severity: "high", text: "Burstiness score: 0.12 — human writing shows much higher variance" },
                { severity: "medium", text: "Sentence length distribution is suspiciously uniform" },
                { severity: "low", text: "Vocabulary richness (TTR: 0.42) indicates templated generation" },
            ],
            hi: [
                { severity: "high", text: "पर्प्लेक्सिटी स्कोर: 42.3 — सामान्य मानवीय लेखन से बहुत कम" },
                { severity: "high", text: "टोकन वितरण GPT-4 आउटपुट से निकटता से मेल खाता है" },
                { severity: "high", text: "बर्स्टीनेस स्कोर: 0.12 — मानवीय लेखन में अधिक भिन्नता होती है" },
                { severity: "medium", text: "वाक्य की लंबाई संदिग्ध रूप से एकसमान है" },
                { severity: "low", text: "शब्दावली समृद्धि (TTR: 0.42) टेम्प्लेटेड जनरेशन का संकेत" },
            ],
        },
        timeline: null,
        heatmap_zones: [],
    },

    whatsapp: {
        file_type: "whatsapp",
        file_name: "whatsapp_forward.jpg",
        overall_confidence: 0.83,
        verdict: "Manipulated + Misleading",
        verdict_color: "red",
        processing_time_ms: 3120,
        sub_scores: { text: 0.76, image: 0.89, audio: null, video: null, metadata: 0.97 },
        cmce_risk: "CRITICAL",
        cmce_detail: "Image is authentic but caption text is fabricated. Context mismatch detected between image context and claim.",
        gan_source: "Image Editing Software",
        gan_confidence: 0.62,
        gan_version: "Photoshop / GIMP",
        viral_risk_score: 0.91,
        viral_risk_label: "Extreme Viral Risk",
        caption_claim: "PM announces free electricity for all — 0 units from Jan 2026",
        caption_verdict: "FALSE — No such announcement found in official sources",
        indicators: {
            en: [
                { severity: "high", text: "Caption claim unverified — not in any official government source" },
                { severity: "high", text: "Image EXIF timestamp: 2023-04-12 — not from claimed 'today'" },
                { severity: "high", text: "Image compressed 6+ times — typical of viral forward chain" },
                { severity: "medium", text: "Text overlay shows font rendering inconsistency" },
                { severity: "low", text: "Reverse image search: same image used in 3 false claims since 2023" },
            ],
            hi: [
                { severity: "high", text: "कैप्शन का दावा असत्यापित — किसी आधिकारिक स्रोत में नहीं मिला" },
                { severity: "high", text: "छवि EXIF टाइमस्टैम्प: 2023-04-12 — दावा किए गए 'आज' की तारीख नहीं" },
                { severity: "high", text: "छवि को 6+ बार संपीड़ित किया गया — वायरल फॉरवर्ड में सामान्य" },
                { severity: "medium", text: "छवि पर टेक्स्ट ओवरले में फ़ॉन्ट रेंडरिंग असंगति है" },
                { severity: "low", text: "रिवर्स इमेज सर्च: 2023 से 3 झूठे दावों में एक ही छवि" },
            ],
        },
        timeline: null,
        heatmap_zones: [
            { top: "5%", left: "5%", width: "90%", height: "20%", label: "Caption text — FABRICATED" },
            { top: "72%", left: "15%", width: "40%", height: "20%", label: "EXIF mismatch region" },
        ],
    },
};

export const ANALYSIS_STEPS = [
    { id: 1, label: "Scanning file metadata & EXIF data…", duration: 600 },
    { id: 2, label: "Running Image Detection Engine (EfficientNet-B4)…", duration: 900 },
    { id: 3, label: "Analyzing GAN noise fingerprints…", duration: 700 },
    { id: 4, label: "Running Cross-Modal Consistency Engine (CMCE)…", duration: 800 },
    { id: 5, label: "Generating GradCAM forensic heatmap…", duration: 600 },
    { id: 6, label: "Attributing to GAN source model…", duration: 500 },
    { id: 7, label: "Scoring viral misinformation risk…", duration: 400 },
    { id: 8, label: "Compiling indicator breakdown…", duration: 300 },
];

export const ANALYSIS_STEPS_VIDEO = [
    { id: 1, label: "Extracting video frames (OpenCV)…", duration: 700 },
    { id: 2, label: "Running Image Engine on sampled frames…", duration: 1000 },
    { id: 3, label: "Analyzing audio track (Wav2Vec 2.0)…", duration: 800 },
    { id: 4, label: "Checking lip-sync synchronization…", duration: 700 },
    { id: 5, label: "Running Cross-Modal Consistency Engine (CMCE)…", duration: 900 },
    { id: 6, label: "Detecting face-swap boundary artifacts…", duration: 600 },
    { id: 7, label: "Building frame-by-frame timeline…", duration: 500 },
    { id: 8, label: "Finalizing results…", duration: 300 },
];

export const ANALYSIS_STEPS_TEXT = [
    { id: 1, label: "Tokenizing text (RoBERTa tokenizer)…", duration: 400 },
    { id: 2, label: "Calculating perplexity score…", duration: 600 },
    { id: 3, label: "Running OpenAI-detector classifier…", duration: 700 },
    { id: 4, label: "Computing burstiness & token variance…", duration: 500 },
    { id: 5, label: "Comparing against GPT/Claude signatures…", duration: 600 },
    { id: 6, label: "Scoring misinformation spread potential…", duration: 400 },
    { id: 7, label: "Generating SHAP token importance map…", duration: 400 },
    { id: 8, label: "Finalizing results…", duration: 300 },
];

export const GAN_SOURCES = {
    "Stable Diffusion XL": { color: "#8B5CF6", icon: "🎨" },
    "DeepFaceLab": { color: "#FF4E6A", icon: "🎭" },
    "ElevenLabs TTS": { color: "#FFB800", icon: "🔊" },
    "GPT-4 / ChatGPT": { color: "#00E87A", icon: "🤖" },
    "Midjourney v6": { color: "#3B82F6", icon: "🖼️" },
    "DALL·E 3": { color: "#F59E0B", icon: "✨" },
    "Image Editing Software": { color: "#6B7280", icon: "✂️" },
};

export const CERT_MOCK = {
    hash: "vv_auth_7a4f2b1c9e8d3a6f0b5c2d1e4f7a8b9c",
    issued_at: new Date().toISOString(),
    verified: true,
    platform: "DRISHTI Authenticity Network",
    standard: "C2PA v1.3 compatible",
};
